type PageContext = { url: string; title: string; text: string; capturedAt: string };
type ElementDetails = { selector: string; tagName: string; text: string; paddingLeft: string; paddingRight: string; marginLeft: string; marginRight: string; display: string; width: string; height: string };
const extensionApi = ((globalThis as unknown as { browser?: typeof browser; chrome?: typeof browser }).browser ?? (globalThis as unknown as { chrome?: typeof browser }).chrome) as typeof browser;
const debugEvents: Record<string, unknown>[] = []; let pickerCleanup: (() => void) | undefined; let injected = false;
function context(): PageContext { return { url: location.href, title: document.title, text: (document.body?.innerText ?? "").replace(/\s+/g, " ").trim().slice(0, 12_000), capturedAt: new Date().toISOString() }; }
function selector(element: Element): string { if (element.id) return `#${CSS.escape(element.id)}`; const classes = [...element.classList].filter(name => !/[0-9a-f]{6,}|^css-/.test(name)).slice(0, 2); const base = `${element.tagName.toLowerCase()}${classes.map(name => `.${CSS.escape(name)}`).join("")}`; const siblings = [...(element.parentElement?.children ?? [])].filter(child => child.tagName === element.tagName); return siblings.length > 1 ? `${base}:nth-of-type(${siblings.indexOf(element) + 1})` : base; }
function inspect(element: Element): ElementDetails { const computed = getComputedStyle(element); const rect = element.getBoundingClientRect(); return { selector: selector(element), tagName: element.tagName.toLowerCase(), text: (element.textContent ?? "").trim().slice(0, 120), paddingLeft: computed.paddingLeft, paddingRight: computed.paddingRight, marginLeft: computed.marginLeft, marginRight: computed.marginRight, display: computed.display, width: `${Math.round(rect.width)}px`, height: `${Math.round(rect.height)}px` }; }
function pick(): Promise<ElementDetails> { pickerCleanup?.(); return new Promise(resolve => { let hovered: HTMLElement | undefined; const move = (event: PointerEvent) => { const target = event.target instanceof HTMLElement ? event.target : undefined; if (target === hovered) return; hovered?.style.removeProperty("outline"); hovered = target; hovered?.style.setProperty("outline", "2px solid #6255e7", "important"); }; const cleanup = () => { document.removeEventListener("pointermove", move, true); document.removeEventListener("click", click, true); hovered?.style.removeProperty("outline"); pickerCleanup = undefined; }; const click = (event: MouseEvent) => { if (!(event.target instanceof Element)) return; event.preventDefault(); event.stopPropagation(); const value = inspect(event.target); cleanup(); resolve(value); }; pickerCleanup = cleanup; document.addEventListener("pointermove", move, true); document.addEventListener("click", click, true); }); }
function override(selectorText: string, property: string, value: string) { const style = document.getElementById("ai-coworker-debug-overrides") as HTMLStyleElement | null ?? Object.assign(document.createElement("style"), { id: "ai-coworker-debug-overrides" }); if (!style.isConnected) document.documentElement.append(style); const rules = style.dataset.rules ? JSON.parse(style.dataset.rules) as Record<string, Record<string, string>> : {}; rules[selectorText] = { ...rules[selectorText], [property]: value }; style.dataset.rules = JSON.stringify(rules); style.textContent = Object.entries(rules).map(([rule, declarations]) => `${rule} { ${Object.entries(declarations).map(([key, current]) => `${key}: ${current} !important;`).join(" ")} }`).join("\n"); }
function enableCapture() { if (!injected) { injected = true; const script = document.createElement("script"); script.src = extensionApi.runtime.getURL("page-debugger.js"); script.onload = () => { script.remove(); window.postMessage({ source: "ai-coworker-debugger", type: "control", enabled: true }, "*"); }; document.documentElement.append(script); } else window.postMessage({ source: "ai-coworker-debugger", type: "control", enabled: true }, "*"); }
window.addEventListener("message", event => { if (event.source === window && event.data?.source === "ai-coworker-debugger" && (event.data.type === "network" || event.data.type === "log")) { debugEvents.push(event.data); if (debugEvents.length > 100) debugEvents.shift(); } });
extensionApi.runtime.onMessage.addListener((message: { type: string; selector?: string; property?: string; value?: string }) => { if (message.type === "GET_PAGE_CONTEXT") { const value = context(); extensionApi.runtime.sendMessage({ type: "PAGE_CONTEXT_UPDATED", context: value }); return Promise.resolve(value); } if (message.type === "DEBUG_PICK_ELEMENT") return pick(); if (message.type === "DEBUG_APPLY_OVERRIDE" && message.selector && message.property && message.value) { override(message.selector, message.property, message.value); return Promise.resolve({ ok: true }); } if (message.type === "DEBUG_CLEAR_OVERRIDES") { document.getElementById("ai-coworker-debug-overrides")?.remove(); return Promise.resolve({ ok: true }); } if (message.type === "DEBUG_ENABLE_CAPTURE") { enableCapture(); return Promise.resolve({ ok: true }); } if (message.type === "DEBUG_GET_DIAGNOSTICS") return Promise.resolve(debugEvents); });
