import { useState } from "react";
import { extensionApi } from "./extension-api";
import { getAccessToken } from "./auth";

type ElementDetails = { selector: string; tagName: string; text: string; paddingLeft: string; paddingRight: string; marginLeft: string; marginRight: string; display: string; width: string; height: string };
type EventRecord = { type: string; status?: number; url?: string; method?: string; duration?: number; message?: string; level?: string };
async function activeTabMessage(message: Record<string, unknown>) { const [tab] = await extensionApi.tabs.query({ active: true, currentWindow: true }); if (!tab?.id) throw new Error("No active tab available"); return extensionApi.tabs.sendMessage(tab.id, message); }
function rca(events: EventRecord[]) { const failed = events.filter(event => event.type === "network" && (event.status === 0 || (event.status ?? 200) >= 400)); const logs = events.filter(event => event.type === "log"); if (!failed.length && !logs.length) return "No failures captured yet. Start capture, reproduce the issue, then analyze again."; const notes = failed.slice(-4).map(event => { if (event.status === 401 || event.status === 403) return `${event.method} ${event.url}: authentication or authorization is being rejected (${event.status}). Check credentials, scopes, and CORS.`; if (event.status === 404) return `${event.method} ${event.url}: endpoint was not found. Check the route, base URL, and deployment version.`; if ((event.status ?? 0) >= 500) return `${event.method} ${event.url}: server-side failure (${event.status}). Correlate with backend logs using the request time.`; if (event.status === 0) return `${event.method} ${event.url}: request did not receive an HTTP response. Check CORS, DNS, connectivity, or a browser block.`; return `${event.method} ${event.url}: client request failed with ${event.status}. Inspect request validation and response details.`; }); if (logs.length) notes.push(`${logs.length} page warning/error log(s) captured. Most recent: ${logs.at(-1)?.message}`); return notes.join("\n\n"); }

export function DebugPanel() {
  const [element, setElement] = useState<ElementDetails>(); const [property, setProperty] = useState("padding-left"); const [value, setValue] = useState(""); const [issue, setIssue] = useState(""); const [analysis, setAnalysis] = useState(""); const [capture, setCapture] = useState(false); const [busy, setBusy] = useState(false);
  const pick = async () => { setBusy(true); try { setElement(await activeTabMessage({ type: "DEBUG_PICK_ELEMENT" }) as ElementDetails); } catch { setAnalysis("Element picking is unavailable on this page."); } finally { setBusy(false); } };
  const preview = async () => { if (!element || !value.trim()) return; await activeTabMessage({ type: "DEBUG_APPLY_OVERRIDE", selector: element.selector, property, value }); setAnalysis(`Preview applied locally. Exact fix: ${element.selector} { ${property}: ${value}; }`); };
  const captureNetwork = async () => { await activeTabMessage({ type: "DEBUG_ENABLE_CAPTURE" }); setCapture(true); setAnalysis("Capture is on. Reproduce the issue, then select Analyze capture."); };
  const analyze = async () => { const events = await activeTabMessage({ type: "DEBUG_GET_DIAGNOSTICS" }) as EventRecord[]; const fallback = rca(events); try { const response = await fetch(`${import.meta.env.VITE_API_BASE_URL}/v1/debug/analyze`, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${await getAccessToken()}` }, body: JSON.stringify({ issue, element, diagnostics: events }) }); const body = await response.json() as { analysis?: string; provider?: string }; if (!response.ok || !body.analysis) throw new Error(); setAnalysis(`${body.analysis}\n\nAnalyzed by: ${body.provider}`); } catch { setAnalysis(fallback); } };
  const inferIssue = () => { if (!element) return; const lower = issue.toLowerCase(); if (lower.includes("padding") && lower.includes("left")) { setProperty("padding-left"); setAnalysis(`Current left padding is ${element.paddingLeft}. Enter a target value, preview it, then copy the exact fix.`); } else setAnalysis("Select a CSS property and target value to preview. This local debugger does not send your page data to an AI service."); };
  return <section className="debug-panel"><div className="debug-intro"><span>Debug mode</span><p>Temporary page changes and in-memory diagnostics only.</p></div><div className="debug-card"><h2>Inspect & override</h2><p>Pick an element on the page, review its box model, then preview a CSS change.</p><button className="debug-button" onClick={pick} disabled={busy}>{busy ? "Select an element on the page…" : "Pick element"}</button>{element && <><dl className="inspect-grid"><div><dt>Element</dt><dd>{element.tagName}</dd></div><div><dt>Size</dt><dd>{element.width} × {element.height}</dd></div><div><dt>Left padding</dt><dd>{element.paddingLeft}</dd></div><div><dt>Right padding</dt><dd>{element.paddingRight}</dd></div></dl><code className="selector">{element.selector}</code><textarea value={issue} onChange={event => setIssue(event.target.value)} placeholder="e.g. This button has extra left padding" rows={2} /><button className="text-button" onClick={inferIssue}>Interpret locally</button><div className="override-row"><select value={property} onChange={event => setProperty(event.target.value)}><option>padding-left</option><option>padding-right</option><option>padding</option><option>margin-left</option><option>margin-right</option><option>font-size</option><option>color</option><option>background-color</option></select><input value={value} onChange={event => setValue(event.target.value)} placeholder="e.g. 12px" /><button className="debug-button" onClick={preview}>Preview</button></div><div className="debug-actions"><button className="text-button" onClick={() => activeTabMessage({ type: "DEBUG_CLEAR_OVERRIDES" })}>Undo previews</button><button className="text-button" onClick={() => navigator.clipboard.writeText(`${element.selector} {\n  ${property}: ${value};\n}`)}>Copy exact fix</button></div></>}</div><div className="debug-card"><h2>Network & console RCA</h2><p>Uses a local LLM first, then OpenRouter, then OpenAI when configured. Otherwise it falls back to local rules.</p><div className="debug-actions"><button className="debug-button" onClick={captureNetwork}>{capture ? "Capture active" : "Start capture"}</button><button className="text-button" onClick={analyze}>Analyze capture</button></div></div>{analysis && <article className="debug-result"><strong>Diagnosis</strong><p>{analysis}</p></article>}</section>;
}
